export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const GET_INITIAL_LIST = 'GET_INITIAL_LIST';
export const GET_INITIAL_LIST_SUCCESS = 'GET_INITIAL_LIST_SUCCESS';
export const GET_FILTERED_LIST_SUCCESS = 'GET_FILTERED_LIST_SUCCESS';
