export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const GET_INITIAL_LIST = 'GET_INITIAL_LIST';
export const GET_PRODUCTS_SUCCES = 'GET_PRODUCTS_SUCCES';
export const ADD_TO_CART = 'ADD_TO_CART';
